import { S3Client, PutObjectCommand } from '@aws-sdk/client-s3';
import dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import mime from 'mime-types';
import { fileURLToPath } from 'url';

// Load environment variables
dotenv.config();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const R2_ACCOUNT_ID = process.env.R2_ACCOUNT_ID;
const R2_ACCESS_KEY_ID = process.env.R2_ACCESS_KEY_ID;
const R2_SECRET_ACCESS_KEY = process.env.R2_SECRET_ACCESS_KEY;
const R2_BUCKET_NAME = process.env.R2_BUCKET_NAME;
const R2_PUBLIC_URL = process.env.R2_PUBLIC_URL;

if (!R2_ACCOUNT_ID || !R2_ACCESS_KEY_ID || !R2_SECRET_ACCESS_KEY || !R2_BUCKET_NAME || !R2_PUBLIC_URL) {
    console.error('❌ Missing R2 environment variables. Please check your .env file.');
    process.exit(1);
}

const s3Client = new S3Client({
    region: 'auto',
    endpoint: `https://${R2_ACCOUNT_ID}.r2.cloudflarestorage.com`,
    credentials: {
        accessKeyId: R2_ACCESS_KEY_ID,
        secretAccessKey: R2_SECRET_ACCESS_KEY,
    },
});

const ASSET_DIRS = [
    path.join(__dirname, '../public/assets'),
    path.join(__dirname, '../src/assets')
];

const OUTPUT_FILE = path.join(__dirname, '../src/config/assetUrls.js');

async function uploadFile(filePath, key) {
    const fileContent = fs.readFileSync(filePath);
    const contentType = mime.lookup(filePath) || 'application/octet-stream';

    try {
        await s3Client.send(new PutObjectCommand({
            Bucket: R2_BUCKET_NAME,
            Key: key,
            Body: fileContent,
            ContentType: contentType,
            // Cache for 1 year
            CacheControl: 'public, max-age=31536000, immutable',
        }));
        console.log(`✅ Uploaded: ${key}`);
        return `${R2_PUBLIC_URL}/${key}`;
    } catch (error) {
        console.error(`❌ Failed to upload ${key}:`, error);
        throw error;
    }
}

async function main() {
    console.log('🚀 Starting asset upload to Cloudflare R2...');

    const assetUrls = {};


    for (const dir of ASSET_DIRS) {
        if (!fs.existsSync(dir)) {
            console.log(`⚠️ Directory not found: ${dir}`);
            continue;
        }

        const files = fs.readdirSync(dir, { recursive: true });

        for (const file of files) {
            // Handle recursive file listing (Node 20+ returns strings, but let's be safe)
            const fullPath = path.join(dir, typeof file === 'string' ? file : file.name);

            // Skip directories
            if (fs.statSync(fullPath).isDirectory()) continue;

            // Skip .DS_Store
            if (path.basename(fullPath) === '.DS_Store') continue;

            const relativePath = path.relative(dir, fullPath);
            // Normalize path separators and create key
            const key = `assets/${relativePath.split(path.sep).join('/')}`;

            // Avoid duplicate uploads if file exists in both src and public
            // (We prioritize the first occurrence, but effectively they should be the same or we overwrite)
            // Actually, let's just upload. R2 is cheap.

            // Create a camelCase key for the JS object
            const filename = path.basename(fullPath, path.extname(fullPath));
            // Simple camelCase conversion
            const objectKey = filename.replace(/[-_](.)/g, (_, c) => c.toUpperCase());

            try {
                const url = await uploadFile(fullPath, key);
                assetUrls[objectKey] = url;
            } catch {
                console.error(`Failed to process ${fullPath}`);
            }
        }
    }

    // Generate assetUrls.js
    const fileContent = `// Auto-generated by scripts/upload-to-r2.js
export const ASSET_URLS = ${JSON.stringify(assetUrls, null, 4)};
`;

    // Ensure directory exists
    const configDir = path.dirname(OUTPUT_FILE);
    if (!fs.existsSync(configDir)) {
        fs.mkdirSync(configDir, { recursive: true });
    }

    fs.writeFileSync(OUTPUT_FILE, fileContent);
    console.log(`\n✨ Asset URLs generated at: ${OUTPUT_FILE}`);
    console.log('🎉 Migration complete!');
}

main().catch(console.error);
